# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Hello World API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"

info:
  version: "0.0.1"
  title: DPS Submission Api
  description: |
    ## Overview
    Use this API to submit data to DPS.

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    - `POST /dps-submission-api`
  contact:
    name: API Management Support
    email: api.management@nhs.net

servers:
  - url: 'https://internal-dev.api.service.nhs.uk/dps-submission-api/'
    description: Sandbox environment.

paths:

  /dps-submission-api/:
    post:
      summary: Submit data and return 200 status to prove that it worked.
      operationId: submitDataToPDS
      description: |
        Get a 200 response from an application restriced endpoint.

      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    example: "{}"
      tags:
        - dps
components:

  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: header
  schemas:
    Greeting:
      $ref: components/schemas/ErrorCode.yaml
